# config.yaml
datapreprocess:
  enc_max_len: 10000 # "whole" for whole sequence
  dec_max_len: 3000 # "whole" for whole sequence
  multiple: 1
  is_raw_count: False # type of count matrix for RNA

model:
  total_gene: 38244  
  max_express: 7
  dim: 280 # should be devided by 7
  enc_depth: 0
  enc_heads: 7
  enc_ff_mult: 4
  enc_dim_head: 140
  enc_emb_dropout: 0.1
  enc_ff_dropout: 0.1
  enc_attn_dropout: 0.1
  dec_depth: 4
  dec_heads: 7
  dec_ff_mult: 4
  dec_dim_head: 140
  dec_emb_dropout: 0.1
  dec_ff_dropout: 0.1
  dec_attn_dropout: 0.1
  
training:
  SEED: 2023
  batch_size: 96
  num_workers: 2
  epoch: 100
  lr: 5e-4
  gamma_step: 4
  gamma: 0.6
  patience: 2 # patience for early stop
